import type { MqttStatus } from '../hooks/useMqtt'
import type { PsdkCommandMethod } from '../types/psdk'
import {
  APP_LANGUAGES,
  APP_LANGUAGE_STORAGE_KEY,
  DEFAULT_APP_LANGUAGE,
  type AppLanguage,
} from '../types/app'

type OnlineState = 'online' | 'offline' | 'unknown'

const APP_TEXT = {
  en: {
    common: {
      na: 'N/A',
      close: 'Close',
      custom: 'custom',
      dismiss: 'Dismiss',
      source: 'Source',
      active: 'active',
      waiting: 'waiting',
      requested: 'Requested',
      ready: 'Ready',
      noWait: 'No wait',
      loading: 'Loading...',
    },
    app: {
      languageLabel: 'Language',
      languageEn: 'EN',
      languageZh: '中文',
      titleTag: 'PSDK MQTT',
      title: 'PSDK Test Console',
      description:
        'Manual control surface for speaker workflows, floating window status, and command diagnostics.',
      footerCreatedBy: 'Created by',
      footerPoweredBy: 'Powered by',
      desktopConfigIncompleteFill: (labels: string) =>
        `Desktop config incomplete. Please fill: ${labels}.`,
      desktopConfigIncompleteMissing: (labels: string) =>
        `Desktop config incomplete. Missing: ${labels}.`,
      desktopConfigSourceLocal: 'Desktop config source: local file.',
      desktopConfigSourceEnv: 'Desktop config source: .env defaults.',
      desktopConfigSourceRenderer:
        'Desktop config source: renderer input (not saved yet).',
      desktopPersistFailed: 'Failed to persist desktop config.',
      alertSequenceRunning:
        'Sequence running. Please wait for it to finish before sending manual commands.',
      alertPsdkOfflineSend:
        'PSDK is offline. Please confirm the device is online before sending commands.',
      alertMqttDisconnectedSend:
        'MQTT not connected. Please connect before sending.',
      alertMissingGatewaySend: 'Missing Gateway SN. Unable to send commands.',
      alertAudioRequired: 'Audio name, URL, and MD5 are required.',
      alertValidateAudioFirst:
        'Please click Validate Audio and wait for a successful result before sending.',
      alertSequenceEmpty: 'Sequence is empty. Please add steps first.',
      alertPsdkOfflineRun:
        'PSDK is offline. Please confirm the device is online before running.',
      alertMqttDisconnectedRun:
        'MQTT not connected. Please connect before running.',
      alertMissingGatewayRun: 'Missing Gateway SN. Unable to run sequence.',
      sequenceStepTimeout: (stepNo: number, method: string) =>
        `Step ${stepNo} (${method}) timed out (10s).`,
      sequenceStepFailure: (
        stepNo: number,
        method: string,
        result: number | string,
      ) => `Step ${stepNo} (${method}) failed (result ${result}).`,
    },
    connection: {
      title: 'Connection',
      subtitle: 'MQTT / Identity',
      stable: 'Connection Stable',
      broker: 'Broker',
      gatewaySn: 'Gateway SN',
      clientId: 'Client ID',
      deviceSn: 'Device SN',
      subscribedTopics: 'Subscribed topics: events, state, services_reply',
      brokerUrlLabel: 'Broker URL',
      gatewaySnLabel: 'Gateway SN',
      usernameLabel: 'Username',
      deviceSnLabel: 'Device SN',
      passwordLabel: 'Password',
      psdkIndexLabel: 'PSDK Index',
      clientIdLabel: 'Client ID',
      autoGenerated: 'Auto-generated',
      brokerPlaceholder: 'ws://broker/mqtt',
      gatewayPlaceholder: 'Gateway serial',
      usernamePlaceholder: 'MQTT username',
      devicePlaceholder: 'Device serial',
      passwordPlaceholder: 'MQTT password',
      connect: 'Connect',
      disconnect: 'Disconnect',
      mqttConnectionFailed: (error?: string | null) =>
        `MQTT connection failed: ${error ?? 'Please verify broker and credentials.'}`,
    },
    speaker: {
      title: 'PSDK Control',
      subtitle: 'Commands',
      pendingSingular: '1 command waiting for services_reply',
      pendingPlural: (count: number) =>
        `${count} commands waiting for services_reply`,
      noPending: 'No pending commands',
      feedbackSuccess: 'Success',
      feedbackTimeout: 'Timeout',
      feedbackFailure: 'Failure',
      resultLabel: 'result',
      playModeVolume: 'Play Mode & Volume',
      playbackActions: 'Playback Actions',
      audioPlayStart: 'Audio Play Start',
      ttsPlayStart: 'TTS Play Start',
      inputBoxTextSet: 'Input Box Text Set',
      widgetValueSet: 'Widget Value Set',
      single: 'Single',
      loop: 'Loop',
      applyMode: 'Apply Mode',
      applyVolume: 'Apply Volume',
      applying: 'Applying...',
      replay: 'Replay',
      replaying: 'Replaying...',
      stop: 'Stop',
      stopping: 'Stopping...',
      example: 'e.g.',
      fileNamePlaceholder: 'File name',
      fileUrlPlaceholder: 'File URL (PCM)',
      fileMd5Placeholder: 'File MD5',
      ttsNamePlaceholder: 'TTS name',
      ttsTextPlaceholder: 'TTS text',
      ttsMd5Placeholder: 'TTS MD5',
      inputBoxPlaceholder: 'Input box content (max 128 bytes/chars)',
      validateAudio: 'Validate Audio',
      validating: 'Validating...',
      waitingReply: 'Waiting Reply...',
      sendAudioPlayStart: 'Send Audio Play Start',
      sendTtsPlayStart: 'Send TTS Play Start',
      setInputBoxText: 'Set Input Box Text',
      setWidgetValue: 'Set Widget Value',
      bytesLabel: (used: number, total: number) => `Bytes: ${used}/${total}`,
      widgetIndex: 'Widget Index',
      widgetValue: 'Widget Value',
      validationPrefixUrl: 'URL/protocol validation failed',
      validationPrefixPcm: 'PCM format validation failed',
      validationPrefixMd5: 'MD5 validation failed',
      validationPrefixNetwork: 'Network/CORS validation error',
    },
    commandResults: {
      title: 'Command Results',
      subtitle: 'services_reply',
      logButton: (count: number) => `Log (${count})`,
      logHint: 'Click Log to view command history in a modal.',
      time: 'Time',
      method: 'Method',
      status: 'Status',
      playProgress: 'Play Progress',
      result: 'Result',
      tid: 'TID',
      empty: 'No commands sent yet.',
    },
    playProgress: {
      title: 'play progress',
      percent: 'Percent',
      step: 'Step',
      status: 'Status',
      tid: 'TID',
      updated: 'Updated',
    },
    floatingWindow: {
      title: 'Floating Window',
      subtitle: 'Latest psdk_floating_window_text',
      currentText: 'Current Text',
      empty: 'No floating window message yet.',
      psdkIndex: 'PSDK Index',
      updated: 'Updated',
    },
    psdkState: {
      title: 'PSDK State',
      subtitle: 'Device / Speaker',
      widgetState: 'widget_state',
      activePayload: 'Active Payload',
      indexLabel: (index: number) => `Index ${index}`,
      name: 'Name',
      sn: 'SN',
      version: 'Version',
      lib: 'Lib',
      lastState: 'Last /state',
      speakerState: 'Speaker State',
      mode: 'Mode',
      playMode: 'Play Mode',
      system: 'System',
      volume: 'Volume',
      file: 'File',
      noStatePayload: 'No /state payload received yet.',
      widgetModalTitle: 'Widget State',
      widgetModalSubtitle: 'config linked view',
      deviceType: 'Device Type',
      linked: 'Linked',
      onlyJsonTip:
        'Only JSON files with config_interface.widget_list are supported.',
      loadingRegistry: 'Loading widget config registry...',
      loadingConfig: (sourceType: string) => `Loading ${sourceType} config...`,
      widgetStatus: 'Widget Status',
      sourceValue: (value: string) => `Source: ${value}`,
      noWidgetValues:
        'No widget values available in current /state payload.',
      waitingCustomUpload:
        'Please upload a valid widget_config.json first. Showing raw index/value only.',
      waitingBuiltinConfig: (sourceType: string) =>
        `Waiting for ${sourceType} config to load. Showing raw index/value only.`,
      noDeviceTypeSelected:
        'No device type selected. Showing raw index/value only.',
      index: 'Index',
      rawValue: 'Raw Value',
      widget: 'Widget',
      type: 'Type',
      state: 'State',
      unmappedWidget: 'Unmapped widget',
      configWithoutValuePrefix: 'Config widgets without /state value',
      fileReadFailed: 'Failed to read file',
      loadRegistryFailed: 'Failed to load widget registry',
    },
    widgetExample: {
      title: 'Widget Example Picker',
      subtitle: 'PSDK config_interface',
      deviceType: 'Device Type',
      widgetActions: 'Widget Actions',
      sourceValue: (value: string) => `Source: ${value}`,
      noDeviceTypeSelected:
        'No device type selected. Please choose one to view widget actions.',
      waitingCustomUpload: 'Please upload a valid widget_config.json first.',
      waitingBuiltinConfig: (sourceType: string) =>
        `Waiting for ${sourceType} config to load...`,
      noWidgets: 'No widgets available in current configuration.',
      expand: 'Expand',
      collapse: 'Collapse',
      scaleValue: 'Scale Value',
      apply: 'Apply',
      noActions: 'No actions available.',
      value: 'value',
      onlyJsonTip:
        'Only JSON files with config_interface.widget_list are supported.',
      fileReadFailed: 'Failed to read file',
      loadRegistryFailed: 'Failed to load widget registry',
    },
    sequence: {
      title: 'Command Sequence',
      subtitle: 'services_reply',
      addStep: 'Add Step',
      runSequence: 'Run Sequence',
      stop: 'Stop',
      clear: 'Clear',
      totalSteps: 'Total Steps',
      currentStep: 'Current Step',
      progress: 'Progress',
      countdown: 'Countdown',
      stopRequest: 'Stop Request',
      defaultWaitSeconds: 'Default wait (sec)',
      stopRequested: 'Stop requested',
      failureDiagnosis: 'Failure diagnosis',
      detail: 'Detail',
      emptyTitle: 'No sequence steps yet.',
      emptyDescription:
        'Build your flow with Add Step, then run it to monitor live status cards.',
      addFirstStep: 'Add First Step',
      step: 'Step',
      collapseDetails: 'Collapse Details',
      expandDetails: 'Expand Details',
      up: 'Up',
      down: 'Down',
      remove: 'Remove',
      commandDetail: 'Command detail',
      wait: 'Wait',
      result: 'Result',
      tid: 'TID',
      defaultWaitSuffix: '(default)',
      runningStep: (current: number, total: number) =>
        `Running step ${current}/${total}`,
      running: 'Running',
      completedSuccess: 'Completed successfully',
      failed: 'Failed',
      stoppedByUser: 'Stopped by user',
      idle: 'Idle',
      failureAtStep: (stepNo: number, total: number, methodLabel: string) =>
        `Failed at step ${stepNo}/${total}: ${methodLabel}`,
      timeoutReason: 'No services_reply was received within 10 seconds.',
      nonZeroResultReason: (result: number | string) =>
        `Received non-zero result: ${result}.`,
      noAdditionalParams: 'No additional parameters required.',
      chooseAnother: 'Choose Another',
      addToSequence: 'Add To Sequence',
      timeout10s: 'timeout (10s)',
    },
    desktopFieldLabels: {
      brokerUrl: 'Broker URL',
      gatewaySn: 'Gateway SN',
      deviceSn: 'Device SN',
    },
  },
  'zh-CN': {
    common: {
      na: '无',
      close: '关闭',
      custom: '自定义',
      dismiss: '忽略',
      source: '来源',
      active: '进行中',
      waiting: '等待中',
      requested: '已请求',
      ready: '可执行',
      noWait: '无等待',
      loading: '加载中...',
    },
    app: {
      languageLabel: '语言',
      languageEn: 'EN',
      languageZh: '中文',
      titleTag: 'PSDK MQTT',
      title: 'PSDK 调试控制台',
      description: '用于喊话器流程、悬浮窗状态与命令诊断的手动控制台。',
      footerCreatedBy: 'Created by',
      footerPoweredBy: 'Powered by',
      desktopConfigIncompleteFill: (labels: string) =>
        `桌面配置不完整，请补全：${labels}。`,
      desktopConfigIncompleteMissing: (labels: string) =>
        `桌面配置不完整，缺少：${labels}。`,
      desktopConfigSourceLocal: '桌面配置来源：本地文件。',
      desktopConfigSourceEnv: '桌面配置来源：.env 默认值。',
      desktopConfigSourceRenderer: '桌面配置来源：界面输入（尚未保存）。',
      desktopPersistFailed: '保存桌面配置失败。',
      alertSequenceRunning: '序列正在执行，请等待结束后再手动发送命令。',
      alertPsdkOfflineSend: 'PSDK 当前离线，请确认设备在线后再发送命令。',
      alertMqttDisconnectedSend: 'MQTT 未连接，请先连接后再发送。',
      alertMissingGatewaySend: '缺少 Gateway SN，无法发送命令。',
      alertAudioRequired: '音频名称、URL 和 MD5 为必填项。',
      alertValidateAudioFirst: '请先点击校验音频，并等待校验成功后再发送。',
      alertSequenceEmpty: '序列为空，请先添加步骤。',
      alertPsdkOfflineRun: 'PSDK 当前离线，请确认设备在线后再运行序列。',
      alertMqttDisconnectedRun: 'MQTT 未连接，请先连接后再运行序列。',
      alertMissingGatewayRun: '缺少 Gateway SN，无法运行序列。',
      sequenceStepTimeout: (stepNo: number, method: string) =>
        `步骤 ${stepNo}（${method}）超时（10 秒）。`,
      sequenceStepFailure: (
        stepNo: number,
        method: string,
        result: number | string,
      ) => `步骤 ${stepNo}（${method}）失败（result ${result}）。`,
    },
    connection: {
      title: '连接配置',
      subtitle: 'MQTT / 身份信息',
      stable: '连接稳定',
      broker: 'Broker',
      gatewaySn: 'Gateway SN',
      clientId: 'Client ID',
      deviceSn: 'Device SN',
      subscribedTopics: '订阅主题：events、state、services_reply',
      brokerUrlLabel: 'Broker URL',
      gatewaySnLabel: 'Gateway SN',
      usernameLabel: '用户名',
      deviceSnLabel: 'Device SN',
      passwordLabel: '密码',
      psdkIndexLabel: 'PSDK Index',
      clientIdLabel: 'Client ID',
      autoGenerated: '自动生成',
      brokerPlaceholder: 'ws://broker/mqtt',
      gatewayPlaceholder: '网关序列号',
      usernamePlaceholder: 'MQTT 用户名',
      devicePlaceholder: '设备序列号',
      passwordPlaceholder: 'MQTT 密码',
      connect: '连接',
      disconnect: '断开',
      mqttConnectionFailed: (error?: string | null) =>
        `MQTT 连接失败：${error ?? '请检查 broker 地址和凭据。'}`,
    },
    speaker: {
      title: 'PSDK 控制',
      subtitle: '命令下发',
      pendingSingular: '1 条命令等待 services_reply',
      pendingPlural: (count: number) => `${count} 条命令等待 services_reply`,
      noPending: '当前无待确认命令',
      feedbackSuccess: '成功',
      feedbackTimeout: '超时',
      feedbackFailure: '失败',
      resultLabel: 'result',
      playModeVolume: '播放模式与音量',
      playbackActions: '播放动作',
      audioPlayStart: '音频播放开始',
      ttsPlayStart: 'TTS 播放开始',
      inputBoxTextSet: '输入框文本设置',
      widgetValueSet: 'Widget 值设置',
      single: '单次',
      loop: '循环',
      applyMode: '应用模式',
      applyVolume: '应用音量',
      applying: '应用中...',
      replay: '重播',
      replaying: '重播中...',
      stop: '停止',
      stopping: '停止中...',
      example: '示例',
      fileNamePlaceholder: '文件名',
      fileUrlPlaceholder: '文件 URL（PCM）',
      fileMd5Placeholder: '文件 MD5',
      ttsNamePlaceholder: 'TTS 名称',
      ttsTextPlaceholder: 'TTS 文本',
      ttsMd5Placeholder: 'TTS MD5',
      inputBoxPlaceholder: '输入框内容（最多 128 字节/字符）',
      validateAudio: '校验音频',
      validating: '校验中...',
      waitingReply: '等待回执...',
      sendAudioPlayStart: '发送音频播放开始',
      sendTtsPlayStart: '发送 TTS 播放开始',
      setInputBoxText: '设置输入框文本',
      setWidgetValue: '设置 Widget 值',
      bytesLabel: (used: number, total: number) => `字节数：${used}/${total}`,
      widgetIndex: 'Widget 索引',
      widgetValue: 'Widget 值',
      validationPrefixUrl: 'URL/协议校验失败',
      validationPrefixPcm: 'PCM 格式校验失败',
      validationPrefixMd5: 'MD5 校验失败',
      validationPrefixNetwork: '网络/CORS 校验失败',
    },
    commandResults: {
      title: '命令结果',
      subtitle: 'services_reply',
      logButton: (count: number) => `日志（${count}）`,
      logHint: '点击日志可在弹窗中查看命令历史。',
      time: '时间',
      method: '方法',
      status: '状态',
      playProgress: '播放进度',
      result: '结果',
      tid: 'TID',
      empty: '暂无已发送命令。',
    },
    playProgress: {
      title: '播放进度',
      percent: '百分比',
      step: '步骤',
      status: '状态',
      tid: 'TID',
      updated: '更新时间',
    },
    floatingWindow: {
      title: '悬浮窗文本',
      subtitle: '最新 psdk_floating_window_text',
      currentText: '当前文本',
      empty: '尚未收到悬浮窗消息。',
      psdkIndex: 'PSDK Index',
      updated: '更新时间',
    },
    psdkState: {
      title: 'PSDK 状态',
      subtitle: '设备 / Speaker',
      widgetState: 'widget_state',
      activePayload: '当前载荷',
      indexLabel: (index: number) => `索引 ${index}`,
      name: '名称',
      sn: 'SN',
      version: '版本',
      lib: '库版本',
      lastState: '最后 /state',
      speakerState: 'Speaker 状态',
      mode: '模式',
      playMode: '播放模式',
      system: '系统状态',
      volume: '音量',
      file: '文件',
      noStatePayload: '尚未收到 /state 载荷。',
      widgetModalTitle: 'Widget 状态',
      widgetModalSubtitle: '配置关联视图',
      deviceType: '设备类型',
      linked: '已关联',
      onlyJsonTip: '仅支持包含 config_interface.widget_list 的 JSON 文件。',
      loadingRegistry: '正在加载 widget 配置索引...',
      loadingConfig: (sourceType: string) => `正在加载 ${sourceType} 配置...`,
      widgetStatus: 'Widget 状态',
      sourceValue: (value: string) => `来源：${value}`,
      noWidgetValues: '当前 /state 载荷中没有 widget 值。',
      waitingCustomUpload:
        '请先上传有效的 widget_config.json，当前仅显示原始 index/value。',
      waitingBuiltinConfig: (sourceType: string) =>
        `等待 ${sourceType} 配置加载完成，当前仅显示原始 index/value。`,
      noDeviceTypeSelected: '未选择设备类型，当前仅显示原始 index/value。',
      index: '索引',
      rawValue: '原始值',
      widget: 'Widget',
      type: '类型',
      state: '状态',
      unmappedWidget: '未映射 Widget',
      configWithoutValuePrefix: '配置中存在但 /state 未返回的 widget',
      fileReadFailed: '读取文件失败',
      loadRegistryFailed: '加载 widget 配置索引失败',
    },
    widgetExample: {
      title: 'Widget 示例选择器',
      subtitle: 'PSDK config_interface',
      deviceType: '设备类型',
      widgetActions: 'Widget 动作',
      sourceValue: (value: string) => `来源：${value}`,
      noDeviceTypeSelected: '未选择设备类型，请先选择后再查看可用动作。',
      waitingCustomUpload: '请先上传有效的 widget_config.json。',
      waitingBuiltinConfig: (sourceType: string) =>
        `正在等待 ${sourceType} 配置加载完成...`,
      noWidgets: '当前配置中没有可用 widget。',
      expand: '展开',
      collapse: '收起',
      scaleValue: '刻度值',
      apply: '应用',
      noActions: '无可用动作。',
      value: '值',
      onlyJsonTip: '仅支持包含 config_interface.widget_list 的 JSON 文件。',
      fileReadFailed: '读取文件失败',
      loadRegistryFailed: '加载 widget 配置索引失败',
    },
    sequence: {
      title: '命令序列',
      subtitle: 'services_reply',
      addStep: '添加步骤',
      runSequence: '运行序列',
      stop: '停止',
      clear: '清空',
      totalSteps: '总步骤',
      currentStep: '当前步骤',
      progress: '进度',
      countdown: '倒计时',
      stopRequest: '停止请求',
      defaultWaitSeconds: '默认等待（秒）',
      stopRequested: '已请求停止',
      failureDiagnosis: '失败诊断',
      detail: '详情',
      emptyTitle: '暂无序列步骤。',
      emptyDescription: '先通过“添加步骤”构建流程，再运行并观察实时状态卡片。',
      addFirstStep: '添加第一个步骤',
      step: '步骤',
      collapseDetails: '收起详情',
      expandDetails: '展开详情',
      up: '上移',
      down: '下移',
      remove: '删除',
      commandDetail: '命令详情',
      wait: '等待',
      result: '结果',
      tid: 'TID',
      defaultWaitSuffix: '（默认）',
      runningStep: (current: number, total: number) =>
        `正在执行步骤 ${current}/${total}`,
      running: '运行中',
      completedSuccess: '执行成功',
      failed: '执行失败',
      stoppedByUser: '已手动停止',
      idle: '空闲',
      failureAtStep: (stepNo: number, total: number, methodLabel: string) =>
        `在步骤 ${stepNo}/${total} 失败：${methodLabel}`,
      timeoutReason: '10 秒内未收到 services_reply。',
      nonZeroResultReason: (result: number | string) =>
        `收到非 0 结果码：${result}。`,
      noAdditionalParams: '该命令无需额外参数。',
      chooseAnother: '重新选择',
      addToSequence: '加入序列',
      timeout10s: '超时（10 秒）',
    },
    desktopFieldLabels: {
      brokerUrl: 'Broker URL',
      gatewaySn: 'Gateway SN',
      deviceSn: 'Device SN',
    },
  },
} as const

const COMMAND_METHOD_LABELS: Record<AppLanguage, Record<PsdkCommandMethod, string>> =
{
  en: {
    speaker_audio_play_start: 'Audio Play Start',
    speaker_tts_play_start: 'TTS Play Start',
    speaker_replay: 'Replay',
    speaker_play_stop: 'Stop',
    speaker_play_mode_set: 'Play Mode Set',
    speaker_play_volume_set: 'Play Volume Set',
    psdk_input_box_text_set: 'Input Box Text Set',
    psdk_widget_value_set: 'Widget Value Set',
  },
  'zh-CN': {
    speaker_audio_play_start: '音频播放开始',
    speaker_tts_play_start: 'TTS 播放开始',
    speaker_replay: '重播',
    speaker_play_stop: '停止',
    speaker_play_mode_set: '播放模式设置',
    speaker_play_volume_set: '播放音量设置',
    psdk_input_box_text_set: '输入框文本设置',
    psdk_widget_value_set: 'Widget 值设置',
  },
}

const MQTT_STATUS_LABELS: Record<AppLanguage, Record<MqttStatus, string>> = {
  en: {
    connected: 'Connected',
    connecting: 'Connecting',
    reconnecting: 'Reconnecting',
    offline: 'Offline',
    error: 'Error',
  },
  'zh-CN': {
    connected: '已连接',
    connecting: '连接中',
    reconnecting: '重连中',
    offline: '离线',
    error: '错误',
  },
}

const ONLINE_STATE_LABELS: Record<AppLanguage, Record<OnlineState, string>> = {
  en: {
    online: 'Online',
    offline: 'Offline',
    unknown: 'Unknown',
  },
  'zh-CN': {
    online: '在线',
    offline: '离线',
    unknown: '未知',
  },
}

const PROGRESS_STEP_LABELS: Record<AppLanguage, Record<string, string>> = {
  en: {
    download: 'Download',
    downloading: 'Downloading',
    prepare: 'Prepare',
    preparing: 'Preparing',
    upload: 'Upload',
    uploading: 'Uploading',
    play: 'Play',
    playing: 'Playing',
    complete: 'Complete',
    completed: 'Completed',
    finish: 'Finish',
    finished: 'Finished',
  },
  'zh-CN': {
    download: '下载',
    downloading: '下载中',
    prepare: '准备',
    preparing: '准备中',
    upload: '上传',
    uploading: '上传中',
    play: '播放',
    playing: '播放中',
    complete: '完成',
    completed: '已完成',
    finish: '结束',
    finished: '已结束',
  },
}

const PROGRESS_STATUS_LABELS: Record<AppLanguage, Record<string, string>> = {
  en: {
    idle: 'Idle',
    pending: 'Pending',
    running: 'Running',
    success: 'Success',
    failure: 'Failure',
    failed: 'Failed',
    timeout: 'Timeout',
    done: 'Done',
    completed: 'Completed',
  },
  'zh-CN': {
    idle: '空闲',
    pending: '等待中',
    running: '运行中',
    success: '成功',
    failure: '失败',
    failed: '失败',
    timeout: '超时',
    done: '完成',
    completed: '已完成',
  },
}

const COMMAND_STATUS_LABELS: Record<
  AppLanguage,
  Record<'pending' | 'success' | 'failure' | 'timeout', string>
> = {
  en: {
    pending: 'pending',
    success: 'success',
    failure: 'failure',
    timeout: 'timeout (10s)',
  },
  'zh-CN': {
    pending: '等待中',
    success: '成功',
    failure: '失败',
    timeout: '超时（10 秒）',
  },
}

const normalizeProgressToken = (value?: string) => {
  if (!value) return undefined
  const normalized = value.trim().toLowerCase()
  return normalized.length > 0 ? normalized : undefined
}

export const toReadableText = (value?: string) => {
  if (!value) return undefined
  return value
    .replace(/[_-]+/g, ' ')
    .split(' ')
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ')
}

export const isAppLanguage = (value: string): value is AppLanguage =>
  APP_LANGUAGES.includes(value as AppLanguage)

export const readStoredLanguage = (): AppLanguage | null => {
  if (typeof window === 'undefined') return null

  try {
    const value = window.localStorage.getItem(APP_LANGUAGE_STORAGE_KEY)
    return value && isAppLanguage(value) ? value : null
  } catch {
    return null
  }
}

export const persistLanguage = (language: AppLanguage) => {
  if (typeof window === 'undefined') return
  try {
    window.localStorage.setItem(APP_LANGUAGE_STORAGE_KEY, language)
  } catch {
    // Ignore localStorage failures in private mode / restricted runtimes.
  }
}

export const detectRuntimeLanguage = (): AppLanguage => {
  if (typeof navigator === 'undefined') return DEFAULT_APP_LANGUAGE

  const candidates = [
    ...(Array.isArray(navigator.languages) ? navigator.languages : []),
    navigator.language,
  ]
    .map((value) => value?.toLowerCase().trim())
    .filter((value): value is string => Boolean(value))

  return candidates.some((value) => value.startsWith('zh')) ? 'zh-CN' : 'en'
}

export const resolveInitialLanguage = (): AppLanguage =>
  readStoredLanguage() ?? detectRuntimeLanguage()

export const getText = (language: AppLanguage) => APP_TEXT[language]

export const getCommandMethodLabel = (
  language: AppLanguage,
  method: PsdkCommandMethod,
) => COMMAND_METHOD_LABELS[language][method] ?? method

export const getMqttStatusLabel = (
  language: AppLanguage,
  status: MqttStatus,
) => MQTT_STATUS_LABELS[language][status]

export const getOnlineStateLabel = (
  language: AppLanguage,
  state: OnlineState,
) => ONLINE_STATE_LABELS[language][state]

export const getProgressStepLabel = (language: AppLanguage, stepKey?: string) => {
  const normalized = normalizeProgressToken(stepKey)
  if (!normalized) return undefined
  return PROGRESS_STEP_LABELS[language][normalized] ?? toReadableText(stepKey)
}

export const getProgressStatusLabel = (
  language: AppLanguage,
  status?: string,
) => {
  const normalized = normalizeProgressToken(status)
  if (!normalized) return undefined
  return PROGRESS_STATUS_LABELS[language][normalized] ?? toReadableText(status)
}

export const getCommandStatusLabel = (
  language: AppLanguage,
  status: 'pending' | 'success' | 'failure' | 'timeout',
) => COMMAND_STATUS_LABELS[language][status]

